### ISSUE TITLE
[gitalk] gitalk 回调地址配置错误

### ISSUE THREAD

**Issue by StringKe** [fujieid/jap-wiki#17]
![image](https://user-images.githubusercontent.com/31089228/135899272-f0fe70ee-5515-4bdf-bdd8-b0dfb494ee8a.png)

完整回调地址: http://localhost:8080/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch

**Comment by zhangyd-c** [comment]
收到，感谢提醒

**Comment by zhangyd-c** [comment]
已经修复！
